font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
font_size 12
window_padding_width 12

# Cursor

cursor_blink_interval 1
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 4

# Theme
include themes/mocha.conf
# background_opacity 0.60
# hide_window_decorations yes
# confirm_os_window_close 0
