##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Daily used
windowrulev2 = float,class:^(clash-verge)$
windowrule = size 500 500,^(Clash Verge)$

windowrulev2 = float,class:^(kitty)$
windowrule = size 1000 700,^(kitty)$

windowrulev2 = float,class:^(wechat)$
windowrule = size 1200 700,^(wechat)$

windowrulev2 = float,class:^(spotify)$
windowrule = size 1200 800,^(spotify)$

# System Control
windowrulev2 = float,title:^(Volume Control)$
windowrule = size 600 400,title:^(Volume Control)$

windowrulev2 = float,class:^(nm-connection-editor)$
windowrule = size 600 400,^(nm-connection-editor)$

windowrulev2 = float,class:^(org.gnome.Nautilus)$
windowrule = size 800 600,^(org.gnome.Nautilus)$

windowrulev2 = float,class:^(nwg-look)$
windowrule = size 600 400,^(nwg-look)$

windowrulev2 = float,class:^(org.fcitx.fcitx5-config-qt)$
windowrule = size 600 400,^(org.fcitx.fcitx5-config-qt)$

windowrulev2 = float,class:^(blueman-manager)$
windowrule = size 600 400,^(blueman-manager)$
# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$

layerrule = blur, logout_dialog
